### ISSUE TITLE
Support for docker.sock

### ISSUE THREAD

**Issue by Crozin** [issuu/sure-deploy#25]
Currently when we want to run sure-deploy as `docker run ...` we need to pass `--host` and `--port` parameters of manager. Can't we add support for `/var/run/docker.sock`? Something like:

`docker run ... -v /var/run/docker.sock:/var/run/docker.sock verify my_stack_name`

**Comment by Leonidas-from-XIV** [comment]
Hi Krzysztof,

Sorry, it took me a while to answer. It currently talks to the manager using their REST API over HTTP because, well, it is easy to talk to HTTP. If I read the [engine API docs](https://docs.docker.com/engine/api/v1.24/) properly the Unix socket API that they offer speaks the same kind of HTTP protocol so in theory it should be doable.

If this is true, it should be possible as a workaround to use `socat` to map the TCP connection into a domain socket. I agree, this is not a great solution, but maybe a decent enough starting point?

**Comment by Crozin** [comment]
@Leonidas-from-XIV Yeah, it's basically the very same protocol (HTTP) just transferred over Unix Named Socked rather TCP one. I wanted to avoid `socat` but if that's needed I'll give it a try.

**Comment by n1ru4l** [comment]
Since I was looking for the same in order to test sure-deploy with Docker for Mac:

```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 127.0.0.1:1234:1234 bobrik/socat TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock
export DOCKER_HOST=tcp://localhost:1234 docker ps
```

**Comment by Crozin** [comment]
@Leonidas-from-XIV any chance UNIX socket support could be added alongside TCP?

**Comment by Leonidas-from-XIV** [comment]
The issue here is that the HTTP library we use, [cohttp](https://github.com/mirage/ocaml-cohttp) uses [conduit](https://github.com/mirage/ocaml-conduit) for communication channels which at the moment only supports TCP and "TLS over TCP". Support for named sockets would need to be added.

**Comment by Leonidas-from-XIV** [comment]
@Crozin I'll see if I can coerce Cohttp (our HTTP library) to talk to the Docker UNIX socket. It sorta supports it, there is code for it, but it does not seem to work.

**Comment by Leonidas-from-XIV** [comment]
I've sent a [PR for Unix domain socket support](https://github.com/mirage/ocaml-cohttp/pull/698) to Cohttp, so it should be possible to support `docker.sock` once this code is upstream.

**Comment by Leonidas-from-XIV** [comment]
Cohttp 2.5.2 will have the change so once that is out I will write the required code in sure-deploy to talk to a domain socket instead of TCP socket.

**Comment by Crozin** [comment]
@Leonidas-from-XIV Just wanted to let you know: works like a harm! 💪  Thank you a lot for your effort.
